import type { Metadata } from 'next';
import { Lilita_One, Montserrat } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/ui/nav-bar';
import RecipeProvider from '@/context/recipe-context';

const montserratFont = Montserrat({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-montserrat',
});
const lilitaFont = Lilita_One({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-lilita-one',
});

export const metadata: Metadata = {
  title: 'Tasty Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${montserratFont.variable}, ${lilitaFont.variable}`}>
        <RecipeProvider>
          <>
            <NavBar />
            {children}
          </>
        </RecipeProvider>
      </body>
    </html>
  );
}
